Update zrep-util
Production version used on ML

diff --git a/zrep-util b/zrep-util
--- a/zrep-util
+++ b/zrep-util
@@ -97,7 +97,7 @@ initializepool() {
   $_command_src zfs snap "$1"@"$_ZFS_TAG"_000000 || { log "[FAILED], exiting now"; return 1; } 
   log "[OK]"
   logne "Creating configuration on source $source..          "
-  $_command_src "$_ZFS_TAG_OPT" zrep changeconfig -f $1 "$destination" "$destination_parent_dataset"/"$1" || { log "[FAILED], exiting now"; return 1; }
+  $_command_src "$_ZFS_TAG_OPT" "$source_zrep_command" changeconfig -f $1 "$destination" "$destination_parent_dataset"/"$1" || { log "[FAILED], exiting now"; return 1; }
   # this puts the file test_pipe on 10.242.0.2
   # ssh root@10.242.0.2 ssh root@10.241.0.1 hostname ">" test_pipe
   log "[OK]"
@@ -127,13 +127,13 @@ resyncpool() {
   snapshot="${1#*@}"
   zreptag "$src_pool"
   # first test whether snaphot given exists on both sides
-  $_command_src zfs list -H -t snapshot -o name -s creation "$1" || { log "given snapshot does not exist on src server, exiting now"; return 1; }
+  $_command_src zfs list -H -t snapshot -o name -s creation "$1" >/dev/null || { log "given snapshot does not exist on src server, exiting now"; return 1; }
   $_command_dst zfs list -H -t snapshot -o name -s creation "$dst_pool"@"$snapshot" || { log "given snapshot does not exist on dst server, exiting now"; return 1; }
-  log "Rolling back to snapshot on destination pool: $dst_pool/$snapshot ...     "
-  $_command_dst zfs rollback -r "$dst_pool"/"$snapshot" || { log "[FAILED], exiting now"; return 1; } 
+  logne "Rolling back to snapshot on destination pool:\n$dst_pool/$snapshot ...     "
+  $_command_dst zfs rollback -r "$dst_pool"@"$snapshot" || { log "[FAILED], exiting now"; return 1; } 
   log "[OK]"
   logne "Resetting last synced snapshot on source $source..          "
-  $_command_src "$_ZFS_TAG_OPT" "$source_zrep_command" sentsync -L "$dst_pool"/"$snapshot" || { log "[FAILED], exiting now"; return 1; }
+  $_command_src "$_ZFS_TAG_OPT" "$source_zrep_command" sentsync -L "$src_pool"@"$snapshot" || { log "[FAILED], exiting now"; return 1; }
   log "[OK]"
   logne "Refresh of zrep backup..                             "
   $_command_dst ZREP_INC_FLAG="-I" "$_ZFS_TAG_OPT" ZREP_PATH="$source_zrep_command" "$destination_zrep_command" refresh "$destination_parent_dataset"/"$1" >/dev/null || { log "[FAILED], exiting now"; return 1; }
@@ -171,6 +171,21 @@ backuppool() {
   return $?
 }
 
+# backup routine, takes pool as argument
+expirepool() {
+  zreptag "$1"
+  if [[ "$2" == "destination" ]]; then
+    log "Expiring snapshots on destination pool "$destination_parent_dataset"/"$1"  ...... "
+    fail_if_stderr $_command_dst ZREP_INC_FLAG="-I" "$_ZFS_TAG_OPT" ZREP_PATH="$source_zrep_command" "$destination_zrep_command" expire -L "$destination_parent_dataset"/"$1"  || { log "[FAILED], exiting now"; return 1; }
+    log "[OK]"
+  else
+    log "Expiring snapshots on source pool $1  ...... "
+    fail_if_stderr $_command_src ZREP_INC_FLAG="-I" "$_ZFS_TAG_OPT" ZREP_PATH="$destination_zrep_command" "$source_zrep_command" expire -L "$1"  || { log "[FAILED], exiting now"; return 1; }
+    log "[OK]"
+  fi
+  return $?
+}
+
 timeelapsed() {
  ((h=${1}/3600))
  ((m=(${1}%3600)/60))
@@ -178,6 +193,16 @@ timeelapsed() {
  output=$(printf "%02d:%02d:%05.2f" $h $m $s )
  log "Runtime: $output time elapsed"
 }
+
+fail_if_stderr() (
+  rc=$({
+    ("$@" 2>&1 >&3 3>&- 4>&-; echo "$?" >&4) |
+    grep '^' >&2 3>&- 4>&-
+  } 4>&1)
+  err=$?
+  [ "$rc" -eq 0 ] || exit "$rc"
+  [ "$err" -ne 0 ] || exit 125
+) 3>&1
 
 initialize() {
   log ""
@@ -227,7 +252,7 @@ resync() {
   RUN_TIMESTAMP=`$DATE_COMMAND '+%s'`
   headerblock true "Start resync to $1 [`$DATE_COMMAND '+%a, %d %b %Y %H:%M:%S (%Z)'`]"
   pool="${1%%@*}"
-  resync "$1"
+  resyncpool "$1"
   if [ "$?" != "0" ]; then
     log "Resync failed"
     ((VAR_COUNT_FAIL++))
@@ -347,6 +372,48 @@ backup() {
   fi
 }
 
+expire(){
+  log ""
+  RUN_TIMESTAMP=`$DATE_COMMAND '+%s'`
+  headerblock true "Start expiring old snapshots [`$DATE_COMMAND '+%a, %d %b %Y %H:%M:%S (%Z)'`]"
+  for pool in "${pools[@]}"
+  do
+    log "Expiring old snapshots on pool $pool"
+    expirepool "$pool" "$1"
+    if [ "$?" != "0" ]; then
+      log "Failed on $pool"
+      ((VAR_COUNT_FAIL++))
+      VAR_FAILED_POOLS+=($pool);
+    else
+      log "Success for $pool"
+    fi
+  done
+  headerblock false "Runtime statistics "
+  log ""
+  log "- Total number of pools: ${#pools[@]}"
+  log "- thereof failed pools: $VAR_COUNT_FAIL"
+
+  if [ "$VAR_COUNT_FAIL" -gt "0" ]; then
+    log "- list of failed pools: "
+    for i in "${VAR_FAILED_POOLS[@]}"
+    do
+      log "- ... $i"
+    done
+  fi
+  log ""
+  END_TIMESTAMP=`$DATE_COMMAND '+%s'`
+  timeelapsed $(( $END_TIMESTAMP-$RUN_TIMESTAMP ))
+  log ""
+  headerblock false "Finished expiring old snapshots [`$DATE_COMMAND '+%a, %d %b %Y %H:%M:%S (%Z)'`]"
+  log ""
+  # If errors occurred on backups, exit with return code 1 instead of 0.
+  if [ "$VAR_COUNT_FAIL" -gt "0" ]; then
+    exit 1
+  else
+    exit 0
+  fi
+}
+
 verify(){
   log ""
   RUN_TIMESTAMP=`$DATE_COMMAND '+%s'`
@@ -393,6 +460,11 @@ verify(){
   fi
 }
 
+
+# load and check configuration
+# srcconfig [skip]
+# skip: optional argument with valid values of src or dst
+#       if given, it will skip validation of the src or dst 
 srcconfig() {
   if ! [[ -f "$cfg_file" ]]; then 
     echo "error: default config file $cfg_file does not exist"
@@ -405,16 +477,18 @@ srcconfig() {
   (( ${#pools[@]} != 0 )) || { echo "error: definition of pools in config file $cfg_file must at least contain one pool"; exit 1; }
   # skip src check (for options backup and verify)
   if ! [[ "$1" == "src" ]]; then
+    src_user="${source%%@*}"
+    src_host="${source#*@}"
     # check login at src 
-    if [[ "$source" =~ .*@.* ]]; then
+    if [[ "$src_host" != "localhost" ]]; then
       _command_src="ssh $source"
       $_command_src echo >/dev/null || { echo "error: failed to login on source server as defined in config file $cfg_file"; exit 1; }
     else
-      if [[ "$source" == $(whoami) ]]; then
+      if [[ "$src_user" == $(whoami) ]]; then
         _command_src="eval"
       else
         if [[ $(whoami) == "root" ]]; then
-          _command_src="su - $source -c"
+          _command_src="su - $src_user -c"
           $_command_src echo >/dev/null || { echo "error: failed to su to src user $source on localhost as defined in config file $cfg_file"; exit 1; }
         else
           echo "error: must be root to switch to src user $source on localhost as defined in config file $cfg_file"; exit 1;
@@ -425,25 +499,29 @@ srcconfig() {
     source_zrep_command=${source_zrep_command:-zrep}
     $_command_src "$source_zrep_command" >/dev/null || { echo "error: failed to execute zrep script on source server as defined in config file $cfg_file"; exit 1; }
   fi
-  # check dataset at backup destination
-  if [[ "$destination" =~ .*@.* ]]; then
-    _command_dst="ssh $destination"
-    $_command_dst echo >/dev/null || { echo "error: failed to login on destination server as defined in config file $cfg_file"; exit 1; }
-  else
-    if [[ "$destination" == $(whoami) ]]; then
-      _command_dst="eval"
+  if ! [[ "$1" == "dst" ]]; then
+    dst_user="${destination%%@*}"
+    dst_host="${destination#*@}"
+    # check login backup destination
+    if [[ "$dst_host" != "localhost" ]]; then
+      _command_dst="ssh $destination"
+      $_command_dst echo >/dev/null || { echo "error: failed to login on destination server as defined in config file $cfg_file"; exit 1; }
     else
-      if [[ $(whoami) == "root" ]]; then
-        _command_dst="su - $destination -c"
-        $_command_dst echo >/dev/null || { echo "error: failed to su to dst user $destination on localhost as defined in config file $cfg_file"; exit 1; }
+      if [[ "$dst_user" == $(whoami) ]]; then
+        _command_dst="eval"
       else
-        echo "error: must be root to switch to dst user $destination on localhost as defined in config file $cfg_file"; exit 1;
+        if [[ $(whoami) == "root" ]]; then
+          _command_dst="su - $dst_user -c"
+          $_command_dst echo >/dev/null || { echo "error: failed to su to dst user $destination on localhost as defined in config file $cfg_file"; exit 1; }
+        else
+          echo "error: must be root to switch to dst user $destination on localhost as defined in config file $cfg_file"; exit 1;
+        fi
       fi
     fi
+    # check zrep command on dst
+    destination_zrep_command=${destination_zrep_command:-zrep}
+    $_command_dst "$destination_zrep_command" >/dev/null || { echo "error: failed to execute zrep script on destination server as defined in config file $cfg_file"; exit 1; }
   fi
-  # check zrep command on dst
-  destination_zrep_command=${destination_zrep_command:-zrep}
-  $_command_dst "$destination_zrep_command" >/dev/null || { echo "error: failed to execute zrep script on destination server as defined in config file $cfg_file"; exit 1; }
   # log file
   logfile=${logfile:-/dev/null}
   [[ -f $logfile ]] || touch $logfile
@@ -452,9 +530,10 @@ srcconfig() {
   custom_flag_src=${custom_flag_src:-}
   custom_flag_dst=${custom_flag_dst:-}
 }
+
 usage() {
   echo "
-initialize, clear or verify zrep backup of zfs pools 
+manage zrep backups of zfs pools 
 
 USAGE: `basename $0` [OPTION] COMMAND [PARAMETER] 
 
@@ -464,6 +543,7 @@ Commands:
   clear                   remove all zrep snapshots and configuration on src
   verify                  verify existence of backups from one day ago on dst
   resync                  roll back to snapshot given as parameter and start sync
+  expire                  expire zrep snapshots based on parameter (source or destination)
 
 Options:
   -c [FILE]               config file, default: zrep_utils.cfg
@@ -491,27 +571,43 @@ while getopts "c:" opt; do
   esac
 done
 shift $(($OPTIND - 1))
-[ $# -eq 1 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
 
-cfg_file=${cfg_file:-zrep_utils.cfg}
-
-if [ "$1" = "initialize" ]; then
-  srcconfig
-  initialize
-elif [ "$1" = "backup" ]; then
-  srcconfig "src"
-  backup
-elif [ "$1" = "clear" ]; then
-  srcconfig
-  clearpools
-elif [ "$1" = "verify" ]; then
-  srcconfig "src"
-  verify
-elif [ "$1" = "resync" ]; then
-  srcconfig
-  resync "$2"
-else
-  #if tty -s; then
-  echo "error: no valid command given"
-  usage
-fi
+case "$1" in
+  "initialize")
+    [ $# -eq 1 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
+    srcconfig
+    initialize
+    ;;
+  "backup")
+    [ $# -eq 1 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
+    srcconfig "src"
+    backup
+    ;;
+  "clear")
+    [ $# -eq 1 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
+    srcconfig
+    clearpools
+    ;;
+  "verify")
+    [ $# -eq 1 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
+    srcconfig "src"
+    verify
+    ;;
+  "resync")
+    [ $# -eq 2 ] || { echo "error: wrong number of arguments"; usage; exit 1; }
+    srcconfig
+    resync "$2"
+    ;;
+  "expire")
+    [ $# -eq 2 ] || { echo "error: wrong number of arguments, please use 'source' or 'destination' as second argument"; usage; exit 1; }
+    case "$2" in
+      "source") srcconfig "dst"; ;;
+      "destination") srcconfig "src";  ;;
+      *) echo "error: wrong argument, please use 'source' or 'destination' as second argument"; usage; exit 1; ;;
+    esac
+    expire "$2"
+    ;;
+  *)
+    echo "error: no valid command given"
+    usage
+esac
